steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/backend/ortiapublic', '.']
    dir: 'fontes/backend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/backend/ortiapublic']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ortiapublicbackend',
      '--image=southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/backend/ortiapublic',
      '--region=southamerica-east1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--port=8080', 
      '--vpc-connector=sql-vpc',
      '--timeout=300s'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/frontend/ortiapublic', '.']
    dir: 'fontes/frontend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/frontend/ortiapublic']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ortiapublicfrontend',
      '--image=southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/frontend/ortiapublic',
      '--region=southamerica-east1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--port=8081',
      '--timeout=300s'
    ]
images:
  - 'southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/backend/ortiapublic'
  - 'southamerica-east1-docker.pkg.dev/ninth-glider-366922/nobuntu/frontend/ortiapublic'
