steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'fontes/backend'
    args: ['build', '-t', 'gcr.io/ninth-glider-366922/ortiapublic/backend', '.']
    secretEnv: ['DATABASE_URL', 'API_KEY']
secrets:
  - kmsKeyName: "projects/ninth-glider-366922/locations/global/keyRings/cloudbuild/cryptoKeys/secrets"
    secretEnv:
      DATABASE_URL: "projects/ninth-glider-366922/secrets/DATABASE_URL/versions/latest"
      API_KEY: "projects/ninth-glider-366922/secrets/API_KEY/versions/latest"
