steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ninth-glider-366922/ortiapublicbackend', '.']
    dir: 'fontes/backend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ninth-glider-366922/ortiapublicbackend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ortiapublicbackend',
      '--image=gcr.io/ninth-glider-366922/ortiapublicbackend',
      '--region=southamerica-east1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--port', '8080', 
      '--timeout=300s'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ninth-glider-366922/ortiapublicfrontend', '.']
    dir: 'fontes/frontend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ninth-glider-366922/ortiapublicfrontend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ortiapublicfrontend',
      '--image=gcr.io/ninth-glider-366922/ortiapublicfrontend',
      '--region=southamerica-east1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--timeout=300s'
    ]
images:
  - 'gcr.io/ninth-glider-366922/ortiapublicbackend'
  - 'gcr.io/ninth-glider-366922/ortiapublicfrontend'