steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ninth-glider-366922/ortiaapp/backend', '-f', 'fontes/backend/Dockerfile', 'fontes/backend/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ninth-glider-366922/ortiaapp/backend']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ortiaappbackend', '--image', 'gcr.io/ninth-glider-366922/ortiaapp/backend', '--region', 'southamerica-east1', '--port', '8080', '--allow-unauthenticated']
